---
- name: Playbook to configure and mount lvm
  hosts: servera
  become: yes
  vars:
    - vgname: falldevops
    - lvname: devopsfall
    - mntpath: '/falldevops'
  tasks:
    - name: Create partition
      parted:
        device: /dev/sdb
        number: 1
        state: present
        flags: [ lvm ]
        part_end: 1GB
        part_type: 'primary'
    - name: Create mountpoint
      file:
        state: 'directory'
        path: "{{ mntpath }}"
        owner: root
        group: root
        mode: '755'
    - name: Create volume group
      lvg:
        vg: "{{ vgname }}"
        state: present
        pvs: /dev/sdb1
    - name: Create logical volume
      lvol:
        vg: "{{ vgname }}"
        lv: "{{ lvname }}"
        size: 500
        state: present
    - name: Make filesystem
      filesystem: 
        fstype: xfs
        dev: "/dev/mapper/{{ vgname }}-{{ lvname }}"
    - name: Mount a filesystem
      mount:
        path: "{{ mntpath }}"
        state: mounted
        src: "/dev/mapper/{{ vgname }}-{{ lvname }}"
        fstype: xfs
        opts: defaults
